export const SELECTED_CATEGORY = "SELECTED_CATEGORY";
export const SELECTED_ITEM = "SELECTED_ITEM";
export const SET_INPUT_FIELD = "SET_INPUT_FIELD";
export const SET_SELECTED_FIELD = "SET_SELECTED_FIELD";
export const SET_SELECTED_CHOICE = "SET_SELECTED_CHOICE";
export const SET_SELECTED_CREDIT_CARD_INPUT = "SET_SELECTED_CREDIT_CARD_INPUT";
export const SET_SELECTED_CREDIT_CARD_INPUT_CHOOSEN = "SET_SELECTED_CREDIT_CARD_INPUT_CHOOSEN";
export const ALL_CATEGORY = "ALL_CATEGORY";
export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_UPDATED = "USER_UPDATED";
export const DELETED_USER_UPDATED = "DELETED_USER_UPDATED";





